// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyauabkczodvhsgyqouq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5YXVhYmtjem9kdmhzZ3lxb3VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njk3MjAsImV4cCI6MjA2NTA0NTcyMH0.0Qt-5fv_OBxzqltbTQR4gdPtwvot9laLBt_vdS4djgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);